version: '3'

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5454:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - $PWD/pgdatadir/data:/var/lib/postgresql/data
      - $PWD/pgdatadir/run:/var/run/postgresql
